language: python

addons:
  apt:
    packages:
      - python-pip
      - python3-pip

sudo: true

os: linux

before_install:
  - sudo pip install pylint
  - cd $TRAVIS_BUILD_DIR/
  - pip install setuptools
  - pip3 install setuptools
  - cd $TRAVIS_BUILD_DIR && pip install -r requirements.txt
  - cd $TRAVIS_BUILD_DIR && pip3 install -r requirements.txt
#  - pylint --version
#  - cd $TRAVIS_BUILD_DIR/libexec/python && pylint $PWD --errors-only --ignore tests  --disable=E0401,E0611

script:
  - bash $TRAVIS_BUILD_DIR/singularity/testing/run_tests.sh $TRAVIS_BUILD_DIR/singularity/testing /tmp
