language: python

sudo: true

os: linux

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pylint
  - cd $TRAVIS_BUILD_DIR/
  - cd $TRAVIS_BUILD_DIR && pip install -r requirements.txt
  - cd $TRAVIS_BUILD_DIR && pip3 install -r requirements.txt
  - pylint --version
#  - cd $TRAVIS_BUILD_DIR/libexec/python && pylint $PWD --errors-only --ignore tests  --disable=E0401,E0611

script:
  - cd $TRAVIS_BUILD_DIR && python -m unittest singularity/testing/test_build.py
  - cd $TRAVIS_BUILD_DIR && python -m unittest singularity/testing/test_package.py
