language: python

sudo: true

os: linux

language: python
python:
  - "2.7"
  - "3.5"

install:
  - pip install pylint
  - cd $TRAVIS_BUILD_DIR/
  - cd $TRAVIS_BUILD_DIR && pip install -r requirements.txt
  - cd $TRAVIS_BUILD_DIR && pip3 install -r requirements.txt
  - python setup.py sdist
  - python setup.py install
  - pylint --version

script:
  - cd $TRAVIS_BUILD_DIR/singularity/tests && python -m unittest test_build.py
  - cd $TRAVIS_BUILD_DIR/singularity/tests && python -m unittest test_package.py
  - cd $TRAVIS_BUILD_DIR/singularity/tests && pylint $PWD --errors-only --ignore tests  --disable=E0401,E0611
